### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by adueppen**
At the moment it's not a toggle button and the code is a bit messy. The color change doesn't seem to apply to SVG icons at the moment and I'm not quite sure why, but everything else seems to work OK enough.

### CODE REVIEW

**Comment by adueppen** [comment]
(comment mentioning #4 for link)

**Comment by adueppen** [comment]
The dark mode *should* be done now but there are some remaining contrast issues with code blocks in dark mode. At the moment I'm using the colors from the sulphurpool-dark color scheme so if we want to change it we might want to consider a different color scheme entirely.

**Comment by crutchcorn** [comment]
Work still needed:

- [ ] Investigate changing some of the CSS with Disqus (this might be possible)
- [ ] Replace the Prism color vars with CSS variables 
- [ ] Add dark mode values to the prism color vars
- [ ] Change the styling of inline code (I believe this is still prism)

**Comment by adueppen** [comment]
OK so the dark code styling should be complete now, I have an idea for how to make the Disqus thing work but I think I might be making a mistake with namespacing.

**Comment by crutchcorn** [comment]
Thank you so much for your patience and consistent dedication to polish for the feature @adueppen

**Pull request merged**
