### PR TITLE
Update: post body line height and heading margins

### PR DESCRIPTION
**Pull request by evelynhathaway**
- Line height 1.7 for post body and post card, 1.5 for headings
- Asymmetrical heading margins as is standard for technical documents
  - Symmetrical if headings are adjacent siblings

### CODE REVIEW

**Comment by crutchcorn** [comment]
I personally think the headers have far too much space. I'd suggest asking @prattidev about this in DMs and getting his thoughts

**Comment by evelynhathaway** [comment]
Are you thinking too much line-height or margin-top? I'm open to changes; I primarily did what was comfortable for me to read in this first go.

**Comment by evelynhathaway** [comment]
Updated this PR with line heights that make more sense for headings, rebased

**Comment by evelynhathaway** [comment]
Additional commit will fix both issues described in #168

**Pull request merged**
