### PR TITLE
Integration merge 05/19/20

### PR DESCRIPTION
**Pull request by crutchcorn**

### CODE REVIEW

**Comment by skatcat31** [comment]
this is just the integration merge to mainline isn't it?

**Comment by crutchcorn** [comment]
@skatcat31 this is the merge to deploy. We have auto hooks that once a merge is made against `master` it deploys to the site

**Comment by skatcat31** [comment]
so yes. Which makes me curious why it needs a review

**Comment by crutchcorn** [comment]
Prevents rogue contributors and separates team-members' permissions a bit more. It requires one approval from a devops person (which is right now either @evelynhathaway or myself)

**Comment by skatcat31** [comment]
I thought the merge system could be set up so that if it were opened by a specific developer it would auto merge and only those devs could open merges to that branch?

**Comment by crutchcorn** [comment]
They could, but this is meant as an added layer of security. I try my best to make sure that the project isn't just mine and my own work is as scrutinized as any other contributor's. This is just one way I've tried to set this up

**Pull request merged**
