### PR TITLE
Pagination support

### PR DESCRIPTION
**Pull request by crutchcorn**
I have a very early version of pagination working, but am limited in pushing it or finalizing it by two features:

- Search
- Filter

I have also yet to add pagination support to author pages yet

Because both of the features currently rely on filtering the list of what's present on the page memory, however the way I'm doing things right now by limiting the graphQL call by using `skip` and `limit`. What we'll need to do is multi-fold:

- [x] Move initial posts shown to JS logic rather than graphql
    This will allow us to do things like changing the items that're shown when the user sorts AFTER using the page results
    - [x] Make sure this is utility based and able to migrate to author pages as well using the same utility
- [x] Implement pagination support during an active filter or search (this will be client-side only. No need to worry about `createPage`)
    - [x] Logic should probably live in a `PostListHandler` component which listens to a Context that has the filter and search results and handles pagination from there
    - [x] When no search or filter are applied, switch back from using client-side sort handling to using the `navigate` method
- [x] In order to avoid memory bloat, the query for the `post-list` page will need to be limited in scope. 
     What I mean by this is that we can't simply use `PostInfo` for the query any further. Another fragment will likely need to be provided in order to have a `PostInfoListDisplay` which we can keep in memory in order to do client-side sort and filtering

One thing that I don't/can't worry about it handling URL changes during search + pagination. This overhead would REQUIRE the user have JavaScript and be extremely challenging to manage. As a result, this behavior will be a known potential improvement with a `DONTFIX` result until the migration to NextJS SSR per #70

### CODE REVIEW

**Comment by crutchcorn** [comment]
Note for @unicorn-utterances/devops - we also need to make a 301 from `/pages/1` to `/`

**Comment by crutchcorn** [comment]
It should also be called out that this seems to compound to the "Go back" button issue mentioned #45.

**Comment by crutchcorn** [comment]
This PR is now done and ready to test. A few notes about testing:

- You'll probably want to change the `postsPerPage` value in the `gatsby-node.js` file to test actual pagination

- Please test filter and search as well. Remember that the page URL may not match. This is known and will not be fixed until after #70 is finished

- Please test both the main page and the author page

**Comment by adueppen** [comment]
So far taking a look at the functionality it seems good, although something that we might want to work on is keeping the page buttons in the same location (whether the next/previous buttons are there or not) since that makes it easier to navigate between pages for me at least.

**Comment by crutchcorn** [comment]
I think make this a fast follow and do so in the next PR

**Comment by evelynhathaway** [comment]
@crutchcorn is the redirect set up?

**Comment by crutchcorn** [comment]
Not yet. I can do so tonight

**Pull request merged**
